{{- $jobName := "" }}
{{- $i := "" }}
{{- $current := "" }}
{{- $affinity := "" }}
{{- $imagepullsecret := "" }}
{{- $resources := "" }}
{{- $start := 0 }}

{{- $nproc_per_node := .Values.MultiprocessingDistributed.nproc_per_node | int  }}
{{- $nnodes := .Values.MultiprocessingDistributed.replicas | int  }}
{{- $image_version := printf "%s:%s" .Values.baseImage.repository .Values.baseImage.tag }}
{{- $namespace := .Release.Namespace | toString }}
{{- $appPrefix := .Values.appPrefix | toString }}

{{- $hfApiKey := .Values.hfApiKey | toString }}
{{- $wandbApiKey := .Values.wandbApiKey | toString }}
{{- $masterAddr  := print $appPrefix "-0." $appPrefix "." $namespace ".svc.cluster.local" }}
{{- $batchSize := .Values.MultiprocessingDistributed.batchSize | int }}
{{- $arch := printf "%s" .Values.MultiprocessingDistributed.arch }}

{{- with .Values.imagePullSecrets }}
    {{- $imagepullsecret = toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.MultiprocessingDistributed.affinity }}
    {{- $affinity = toYaml . | nindent 12 }}
{{- end }}

{{- with .Values.MultiprocessingDistributed.resources }}
    {{- $resources = toYaml . | nindent 12 }}
{{- end }}

{{- range untilStep $start $nnodes 1 }}
  {{- $i = . | toString }}
  {{- $jobName = print $appPrefix "-" $i }}
  {{- $current = print $jobName "." $appPrefix "." $namespace ".svc.cluster.local:5005" | quote }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $appPrefix }}
spec:
  ttlSecondsAfterFinished: 20
  template:
    metadata:
      labels: 
        app: {{ $appPrefix }}
    spec:
      affinity: 
    {{ $affinity }}
      imagePullSecrets:
    {{ $imagepullsecret }}
      subdomain: {{ $appPrefix }}
      hostname: {{ $jobName }}
      restartPolicy: Never
      containers: 
        - name: {{ $jobName }}
          image: {{ $image_version }}
          imagePullPolicy: Always
          resources:
        {{- $resources }}
          ports:
            - name: workers
              containerPort: 5005 
          args: 
            - torchrun
            - --nproc_per_node={{ $nproc_per_node }}
            - --nnodes={{ $nnodes }}
            - --node_rank={{ $i }}
            - --rdzv_backend=c10d
            - --rdzv_endpoint={{ $masterAddr }}:5005
            - finetuning.py
            - --enable_fsdp
            - --model_name=/model-storage/meta-llama/Meta-Llama-3-8B 
            - --output_dir=/workspace/data/checkpoints
            - --dist_checkpoint_root_folder=data/fsdp-checkpoints
            - --dist_checkpoint_folder=test-job
            - --dataset="llamaguard_toxicchat_dataset"
            - --fsdp_config.pure_bf16
            - --use_fast_kernels
            - --batch_size_training=8
            - --num_workers_dataloader=8
            - --num_epochs=5
            # - --use-wandb
            # - --sharding_strategy=HYBRID_SHARD
          env:
            - name: OMPI_ALLOW_RUN_AS_ROOT
              value: "1"
            - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
              value: "1"
            - name: NCCL_COLLNET_ENABLE
              value: "0"
            - name: SHARP_COLL_ENABLE_PCI_RELAXED_ORDERING
              value: "1"
            - name: UCX_NET_DEVICES
              value: "mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1"
            - name: NCCL_IB_HCA
              value: "mlx5"
            - name: MAX_ACC_OUT_READ
              value: "128"
            - name: TORCH_NCCL_ASYNC_ERROR_HANDLING
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: CUDA_DEVICE_MAX_CONNECTIONS
              value: "1"
            - name: NCCL_IB_SL
              value: "1"
            - name: NCCL_TOPO_FILE
              value: "/topo-config/nccl-topo-h100-v1.xml"
            - name: NCCL_SOCKET_IFNAME
              value: "=eth0"
            - name: TORCH_DISTRIBUTED_DEBUG
              value: INFO
            - name: NCCL_DEBUG
              value: INFO
            - name: CUDA_LAUNCH_BLOCKING
              value: "0"
            - name: WANDB_API_KEY
              value: "{{ $wandbApiKey }}"
            - name: HF_TOKEN
              value: "{{ $hfApiKey }}"
          securityContext:
              privileged: true
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /workspace/data
            # - name: ib
            #   mountPath: /dev/infiniband
            - mountPath: /topo-config
              name: topo-config-volume
            - mountPath: /model-storage
              name: model-storage-volume
    {{ if gt . 0 }}
      initContainers:
        - name: "init-{{ $jobName }}-connection"
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ print $appPrefix "-0." $appPrefix "." $namespace ".svc.cluster.local" | quote }}; do echo waiting for head node...; sleep 10; done']
    {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: {{ $appPrefix }}
        # - name: ib
        #   hostPath:
        #     path: /dev/infiniband
        - name: topo-config-volume
          configMap:
            name: topo-config
        - name: model-storage-volume
          persistentVolumeClaim:
            claimName: csi-s3-model-storage-pvc-v1 
            readOnly: false
{{- end }}