kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.appPrefix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appPrefix }}
spec:
  storageClassName: hostpath
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/filestore/checkpoints"
