apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ .Values.appPrefix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appPrefix }}
spec:
  storageClassName: csi-mounted-fs-path-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi